language: go
dist: bionic
cache:
  directories:
    - $GOPATH/pkg
before_install:
  - export GOCACHE=$GOPATH/pkg/cache
install:
  - go mod download
script:
  - find fixtures/ -type f -name '*.proto' -print0 | xargs --null --max-args=1 protoc --descriptor_set_out=/dev/null --proto_path=fixtures --proto_path=fixtures/include
  - go test -v ./...
  - go vet -v ./...
env:
  global:
    - GO111MODULE=on
go:
  - 1.x
addons:
  apt:
    packages:
      - protobuf-compiler
